### ISSUE TITLE
Stops within a few seconds of starting

### ISSUE THREAD

**Issue by wiljums** [darkrain-nl/home-assistant-addon-s0pcm-reader#15] opened 2024-04-06 12:25 UTC
debug log:

s6-rc: info: service s6rc-oneshot-runner: starting s6-rc: info: service s6rc-oneshot-runner successfully started s6-rc: info: service fix-attrs: starting s6-rc: info: service fix-attrs successfully started s6-rc: info: service legacy-cont-init: starting cont-init: info: running /etc/cont-init.d/config.sh cont-init: info: /etc/cont-init.d/config.sh exited 0 s6-rc: info: service legacy-cont-init successfully started s6-rc: info: service legacy-services: starting s6-rc: info: service legacy-services successfully started ----------------------------------------------------------- Add-on: S0PCM Reader S0PCM reader based on docker-s0pcm-reader ----------------------------------------------------------- Add-on version: 0.8.2 You are running the latest version of this add-on. System: Debian GNU/Linux 11 (bullseye) (aarch64 / raspberrypi3-64) Home Assistant Core: 2024.4.1 Home Assistant Supervisor: 2024.03.1 ----------------------------------------------------------- Please, share the above information when looking for help or support in GitHub. ----------------------------------------------------------- 2024-04-06 14:08:23,103 INFO: Start: s0pcm-reader - version: 2024.02.17 2024-04-06 14:08:23,132 DEBUG: Config: {'log': {'level': 'DEBUG', 'size': 10485760, 'count': 3}, 'mqtt': {'host': 'core-mosquitto', 'port': '1883', 'base_topic': 's0pcmreader', 'username': 'addons', 'password': 'xx', 'client_id': 'None', 'retain': True, 'split_topic': True, 'tls': False, 'tls_ca': '', 'tls_check_peer': True, 'connect_retry': 5, 'version': <MQTTProtocolVersion.MQTTv5: 5>, 'online': 'online', 'offline': 'offline', 'lastwill': 'offline'}, 'serial': {'port': '/dev/ttyACM0', 'baudrate': 9600, 'connect_retry': 5, 'parity': 'E', 'stopbits': 1, 'bytesize': 7, 'timeout': None}, 's0pcm': {'publish_interval': 10, 'publish_onchange': True, 'include': [1, 2, 3, 4, 5], 'dailystat': None}} 2024-04-06 14:08:23,165 ERROR: Fatal exception has occured Traceback (most recent call last): File "/usr/src/s0pcm-reader.py", line 649, in <module> ReadMeasurement() File "/usr/src/s0pcm-reader.py", line 251, in ReadMeasurement if 'date' in measurement: ^^^^^^^^^^^^^^^^^^^^^ TypeError: argument of type 'NoneType' is not iterable s6-rc: info: service legacy-services: stopping s6-rc: info: service legacy-services successfully stopped s6-rc: info: service legacy-cont-init: stopping s6-rc: info: service legacy-cont-init successfully stopped s6-rc: info: service fix-attrs: stopping s6-rc: info: service fix-attrs successfully stopped s6-rc: info: service s6rc-oneshot-runner: stopping s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by darkrain-nl** [comment] 2024-04-06 15:58
Hi thanks for reporting this.

Could you please check the `measurement.yaml` file in the folder `/share/s0pcm`?
Does it look similar to:
```
date: 2024-04-06
1:
  pulsecount: 0
  today: 257
  total: 1139857
  yesterday: 198
2:
  pulsecount: 0
  today: 0
  total: 0
  yesterday: 0
```

I cannot reproduce the error, so I hope we can figure it out together..

**Comment by darkrain-nl** [comment] 2024-04-06 17:16
I have just released version v0.8.3 that should help in the investigation, would you mind testing this version?

**Comment by wiljums** [comment] 2024-04-06 19:01
I will, can I force the update?

**Comment by darkrain-nl** [comment] 2024-04-06 19:09
You should be able to check for updates on the add-on store, then it should show..

**Comment by wiljums** [comment] 2024-04-06 20:21
the measurement.yaml was somehow empty. I added the content and now it is working again.

**Comment by darkrain-nl** [comment] 2024-04-07 04:58
Ah good to hear, I will go ahead and improve the handling of such situation in a future release.
Will close this one.

**Closed as completed by darkrain-nl** 2024-04-07 04:58 UTC
